(function(){
const api='';
const state={caseId:null,taskId:null,knowledge:null,overview:null};
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pretty=v=>JSON.stringify(v,null,2);
const fmt=v=>{if(!v)return'—';const d=new Date(v);return Number.isNaN(d.getTime())?String(v):d.toLocaleString('zh-CN',{hour12:false})};
function toast(msg,bad=false){const el=$('toast');el.textContent=msg;el.className='toast show'+(bad?' bad':'');clearTimeout(toast.t);toast.t=setTimeout(()=>el.className='toast',2600)}
async function request(path,options={}){const res=await fetch(api+path,{headers:{'Content-Type':'application/json'},...options});const text=await res.text();let data=null;try{data=text?JSON.parse(text):null}catch{data=text}if(!res.ok)throw new Error(typeof data?.detail==='string'?data.detail:(text||res.statusText));return data}
function status(v){const cls=['completed','resolved','active'].includes(v)?'ok':['failed','blocked','cancelled','timed_out'].includes(v)?'bad':'live';return`<span class="status ${cls}">${esc(v)}</span>`}
function setConnected(ok,detail){$('connection-dot').className=ok?'ok':'bad';$('connection-label').textContent=ok?'connected':'offline';$('connection-detail').textContent=detail||location.host}
function show(view){document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===`view-${view}`));document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===view));$('view-title').textContent={overview:'运行态',knowledge:'Knowledge',cases:'Investigation',tasks:'Task Runtime'}[view]}
document.querySelectorAll('.nav-item').forEach(b=>b.addEventListener('click',()=>show(b.dataset.view)));
setInterval(()=>$('clock').textContent=new Date().toLocaleString('zh-CN',{hour12:false}),1000);

async function loadOverview(){const v=await request('/api/v1/workbench/overview');state.overview=v;$('m-revision').textContent=v.latest_knowledge_revision;$('m-sources').textContent=v.source_count;$('m-source-note').textContent=v.source_failure_count?`${v.source_failure_count} source failures`:'runtime owners';$('m-objects').textContent=v.object_count;$('m-cases').textContent=`${v.active_case_count}/${v.case_count}`;$('m-tasks').textContent=`${v.running_task_count}/${v.task_count}`;$('m-model').textContent=v.model_configured?'ON':'OFF';setConnected(true,`${v.environment} · ${location.host}`)}
async function loadSources(){const[cov,rows]=await Promise.all([request('/api/v1/workbench/evaluation/source-coverage'),request('/api/v1/workbench/sources?limit=300')]);$('coverage').textContent=`${cov.supported_source_categories.length}/8 executable categories`;$('source-body').innerHTML=rows.map(x=>`<tr><td><strong>${esc(x.source_id)}</strong></td><td>${esc(x.source_class)}<small>${esc(x.source_role)}</small></td><td><code>${esc(x.retention_mode)}</code><small>${esc(x.access_mode)}</small></td><td>${fmt(x.last_success_at)}</td><td>${x.consecutive_failures?`<span class="status bad">${x.consecutive_failures}</span>`:'<span class="status ok">0</span>'}</td><td>${fmt(x.next_due_at)}</td></tr>`).join('')||'<tr><td colspan="6">no source state</td></tr>'}
async function loadAll(){try{await Promise.all([loadOverview(),loadSources(),loadCases(),loadTasks()])}catch(e){setConnected(false,e.message);toast(e.message,true)}}
$('refresh-all').addEventListener('click',loadAll);

function renderKnowledge(v){const claims=v.claims||[],rels=v.relations||[];$('knowledge-empty').classList.add('hidden');const root=$('knowledge-detail');root.classList.remove('hidden');root.innerHTML=`<section class="panel"><div class="knowledge-head"><div><span class="kicker">${esc(v.object_type)}</span><h2>${esc(v.canonical_key)}</h2></div><code>${esc(v.object_id)}</code></div><div class="knowledge-grid"><div class="record-panel"><h3>Claims · ${claims.length}</h3>${claims.map(x=>`<div class="record"><div><strong>${esc(x.predicate)}</strong><p>${esc(pretty(x.value))}</p></div><small>rev ${x.created_revision}<br>${(x.evidence||[]).length} evidence</small></div>`).join('')||'<p class="kicker">NO CLAIMS</p>'}</div><div class="record-panel"><h3>Relations · ${rels.length}</h3>${rels.map(x=>`<div class="record"><div><strong>${esc(x.relation_type)}</strong><p>${esc(x.target?.canonical_key)}</p></div><small>rev ${x.created_revision}<br>${(x.evidence||[]).length} evidence</small></div>`).join('')||'<p class="kicker">NO RELATIONS</p>'}</div></div></section>`}
async function lookup(){const cve=$('cve-input').value.trim().toUpperCase();if(!cve)return;try{const v=await request(`/api/v1/vulnerabilities/${encodeURIComponent(cve)}`);state.knowledge=v;$('enrich-cve').disabled=false;$('case-cve').value=cve;renderKnowledge(v)}catch(e){toast(e.message,true)}}
$('lookup-cve').addEventListener('click',lookup);$('cve-input').addEventListener('keydown',e=>{if(e.key==='Enter')lookup()});
$('enrich-cve').addEventListener('click',async()=>{if(!state.knowledge)return;try{const cve=$('cve-input').value.trim().toUpperCase();const r=await request('/api/v1/workbench/enrichment',{method:'POST',body:JSON.stringify({cve_id:cve,object_id:state.knowledge.object_id})});toast(`enrichment queued · ${r.celery_task_id}`);setTimeout(loadTasks,900)}catch(e){toast(e.message,true)}});

function card(item,type){const id=type==='case'?item.case_id:item.run_id;const selected=type==='case'?state.caseId===id:state.taskId===id;const title=type==='case'?item.goal:item.task_kind;const sub=type==='case'?`${item.task_signature} · rev ${item.current_revision}`:`${item.role_id} · ${fmt(item.updated_at)}`;return`<button class="list-card ${selected?'selected':''}" data-${type}-id="${esc(id)}"><div><strong>${esc(title)}</strong><small>${esc(sub)}</small></div>${status(item.status)}</button>`}
async function loadCases(){const rows=await request('/api/v1/workbench/cases?limit=100');$('case-list').innerHTML=rows.map(x=>card(x,'case')).join('')||'<div class="kicker">NO CASES</div>';document.querySelectorAll('[data-case-id]').forEach(b=>b.addEventListener('click',()=>selectCase(b.dataset.caseId)))}
function bucket(name,rows){return`<div class="bucket"><h3>${name} · ${rows.length}</h3>${rows.map(x=>`<div class="bucket-item"><strong>${esc(x.proposition)}</strong><small>${(x.evidence_refs||[]).length} evidence · rev ${x.updated_revision}</small></div>`).join('')||'<span class="kicker">EMPTY</span>'}</div>`}
async function selectCase(id){state.caseId=id;await loadCases();const v=await request(`/api/v1/workbench/cases/${encodeURIComponent(id)}`),s=v.state,needs=v.evidence_needs||[],tr=v.trajectories||[],sn=v.snapshots||[];$('case-detail').innerHTML=`<div class="detail-wrap"><div class="detail-title"><div><span class="kicker">${esc(v.case.status)} · CASE REV ${s.case_revision}</span><h2>${esc(v.case.goal)}</h2></div><code>${esc(id)}</code></div><div class="bucket-grid">${bucket('CONFIRMED',s.confirmed||[])}${bucket('CONFLICTS',s.conflicts||[])}${bucket('UNKNOWNS',s.unknowns||[])}${bucket('HYPOTHESES',s.hypotheses||[])}</div><div class="subhead"><h3>EvidenceNeed · ${needs.length}</h3><div class="run-controls"><select id="run-kind"><option>investigate_relation</option><option>verify_version_fix</option><option>resolve_conflict</option><option>investigate_incident</option><option>watch_incident</option><option>assess_normative_applicability</option><option>observe_live_asset</option></select><button id="start-run" class="button primary" ${needs.length?'':'disabled'}>启动 Task</button></div></div>${needs.map(x=>`<div class="record"><div><strong>${esc(x.proposition_or_question)}</strong><p>${esc(x.purpose)}</p></div><small>${esc(x.status)} · P${x.priority}</small></div>`).join('')||'<span class="kicker">NO EVIDENCE NEED</span>'}<div class="decision-box"><div class="decision-actions"><span>M6 CURRENT DECISION</span><button id="run-decision" class="button ghost" ${state.overview?.model_configured?'':'disabled'}>运行 M6</button></div><pre id="decision-raw" class="raw">${esc(pretty(s.current_decision))}</pre></div><div class="subhead"><h3>M7 coordinates</h3><span class="kicker">${tr.length} trajectory · ${sn.length} snapshot</span></div><pre class="raw">${esc(pretty({trajectories:tr,snapshots:sn}))}</pre></div>`;$('start-run')?.addEventListener('click',()=>startRun(id,needs));$('run-decision')?.addEventListener('click',()=>runDecision(id))}
$('case-form').addEventListener('submit',async e=>{e.preventDefault();try{const r=await request('/api/v1/workbench/cases',{method:'POST',body:JSON.stringify({cve_id:$('case-cve').value.trim().toUpperCase(),goal:$('case-goal').value.trim(),evidence_question:$('case-question').value.trim()})});await loadCases();await selectCase(r.case.case_id);toast('Case created')}catch(err){toast(err.message,true)}});
async function startRun(id,needs){const open=needs.filter(x=>['open','blocked'].includes(x.status));try{const r=await request(`/api/v1/workbench/cases/${encodeURIComponent(id)}/runs`,{method:'POST',body:JSON.stringify({task_kind:$('run-kind').value,required_need_ids:open.map(x=>x.need_id)})});show('tasks');await loadTasks();await selectTask(r.run.run_id);toast(`Task queued · ${r.run.run_id.slice(0,8)}`)}catch(e){toast(e.message,true)}}
async function runDecision(id){const out=$('decision-raw');out.textContent='M6 running…';try{const r=await request(`/api/v1/workbench/cases/${encodeURIComponent(id)}/decision`,{method:'POST'});out.textContent=pretty(r);await loadCases()}catch(e){out.textContent=e.message;toast(e.message,true)}}

async function loadTasks(){const rows=await request('/api/v1/workbench/tasks?limit=100');$('task-list').innerHTML=rows.map(x=>card(x,'task')).join('')||'<div class="kicker">NO TASKS</div>';document.querySelectorAll('[data-task-id]').forEach(b=>b.addEventListener('click',()=>selectTask(b.dataset.taskId)))}
async function selectTask(id){state.taskId=id;await loadTasks();const v=await request(`/api/v1/workbench/tasks/${encodeURIComponent(id)}`),events=v.events||[];$('task-detail').innerHTML=`<div class="detail-wrap"><div class="detail-title"><div><span class="kicker">${esc(v.run.status)} · ${esc(v.run.role_id)}</span><h2>${esc(v.contract.task_kind)}</h2></div><code>${esc(id)}</code></div><div class="subhead"><h3>TaskEvent</h3><span class="kicker">${events.length} durable events</span></div>${events.map(e=>`<div class="event"><span>${String(e.seq).padStart(2,'0')}</span><div><strong>${esc(e.event_type)}</strong><small>${esc(e.producer)} · ${fmt(e.emitted_at)}</small></div><code>${esc(e.payload_ref)}</code></div>`).join('')}<div class="subhead"><h3>TaskContract</h3></div><pre class="raw">${esc(pretty(v.contract))}</pre><div class="subhead"><h3>ContextManifest</h3></div><pre class="raw">${esc(pretty(v.context))}</pre></div>`}

loadAll();
})();
